const MOVIE_TYPE = {
    FETCH_MOVIES: "FETCH_MOVIES",
    FETCH_MOVIE_DETAIL: "FETCH_MOVIE_DETAIL",
    SEARCH_MOVIE: "SEARCH_MOVIE",
    FETCH_FAVORITE_MOVIES: "FETCH_FAVORITE_MOVIES",
}
export default MOVIE_TYPE